- what is a dataframe (pandas)
- create df
- vectorized operations
- access rows, columns, and cells. (.loc, .iloc, .at)
- change values
- sort values

In [1]:
import pandas as pd

In [18]:

data_list: list[int] = [1,2,3,4,5]

s1 = pd.Series(data_list)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [20]:
s1 = pd.Series(data = data_list, index=["a", "b", "c", "d", "e"])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
s1  = s1 + 23 
s1

In [ ]:
type(s1)

In [ ]:
# DF = collection of series of objects 

# dictionary creation 
data = {
    "name": ["Nate", "Rebecca", "Edwin", "Preston"],
    "age": [39, 40, 11, 7],
    "year": ["Senior", "Junior", "sophmore", "freshman"]
}
students_df = pd.DataFrame(data = data)
students_df = students_df.set_index("name")
students_df

         age      year
name
Nate      39    Senior
Rebecca   40    Junior
Edwin     11  sophmore
Preston    7  freshman

In [24]:
students_df = students_df.reset_index

students_df

AttributeError: 'function' object has no attribute 'reset_index'

In [25]:
# Row - based creation

import random 

names = ["Messi", "Ronaldo", "Neymar", "Pulisc","Mbappe"]
goals_per_game = [random.random() for _ in names]
games = [round(random.random() * 1000) for _ in names]
games

cols = ["names", "goals/game", "game"]
stats = [[names[i], goals_per_game[i], games[i]] for i in range(5)]
stats_df = pd.DataFrame(data = stats, columns = cols)
stats_df

     names  goals/game  game
0    Messi    0.966746   104
1  Ronaldo    0.091745   977
2   Neymar    0.877318   331
3   Pulisc    0.472496   744
4   Mbappe    0.948172   937

In [26]:
stats_df["new_col"] = 0 
stats_df

     names  goals/game  game  new_col
0    Messi    0.966746   104        0
1  Ronaldo    0.091745   977        0
2   Neymar    0.877318   331        0
3   Pulisc    0.472496   744        0
4   Mbappe    0.948172   937        0

In [27]:
stats_df = stats_df.drop(columns=["new_col"])
stats_df

     names  goals/game  game
0    Messi    0.966746   104
1  Ronaldo    0.091745   977
2   Neymar    0.877318   331
3   Pulisc    0.472496   744
4   Mbappe    0.948172   937

In [37]:
stats_df['goals'] = stats_df["goals/game"] 
stats_df

     names  goals/game  game     goals
0    Messi    0.966746   104  0.966746
1  Ronaldo    0.091745   977  0.091745
2   Neymar    0.877318   331  0.877318
3   Pulisc    0.472496   744  0.472496
4   Mbappe    0.948172   937  0.948172

In [45]:
stats_df = stats_df.rename(columns = {"goals/game": "goals_per_game"})

AttributeError: 'list' object has no attribute 'rename'

In [48]:
stats_df["name"] = stats_df["name"].str.lower()
stats_df

TypeError: list indices must be integers or slices, not str

In [5]:
# filtering with .loc

stats_df.loc[0,"names"]

NameError: name 'stats_df' is not defined

In [8]:
stats_df.loc[:, "names"]

NameError: name 'stats_df' is not defined